name: AWS CD
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - homolog
      - prod
jobs:
  DeployToAWS:
    environment: 
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
        - uses: actions/checkout@v3
        - name: Setup AWS Credentials
          run: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region ${{ secrets.AWS_REGION }}
            aws configure set default.output json

        - name: Setting stage and stack name
          run: |
            echo "STAGE=${{ github.ref_name }}" 
            echo "STACK_NAME=${{ secrets.STACK_NAME }}"
    
        - name: Installing Dependencies to Deploy
          run: |
            cd iac
            npm i -g aws-cdk ts-node
            npm i
        - name: Installing Dependencies to AppRoleMailService
          run: |
            npm i
            npm run build
        - name: Setup envs
          run: |
            echo AWS_REGION=${{ secrets.AWS_REGION }} >> $GITHUB_ENV
            echo AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} >> $GITHUB_ENV
            echo GITHUB_REF=${{ github.ref_name }} >> $GITHUB_ENV

            echo ${{ env.AWS_REGION }}
            echo ${{ env.AWS_ACCOUNT_ID }}
            echo ${{ env.STACK_NAME }}
            echo ${{ env.GITHUB_REF }}

        - name: Deploy with CDK
          run: |
            cd iac
            ts-node node_modules_adjust.ts
            cdk synth
            cdk deploy --require-approval never 

          env:
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
            STACK_NAME: ${{ secrets.STACK_NAME }}
            GITHUB_REF: ${{ github.ref_name }}
       